/** Spatial shelf editing against disposable Auth/PostgREST and the production Worker. */
import { firefox, expect, type BrowserContext, type Locator, type Page } from '@playwright/test';
import { strict as assert } from 'node:assert';
import { randomUUID } from 'node:crypto';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fieldLabel, captureFailure, proofEnvironment } from './web-proof/harness';
import { en } from '../src/lib/i18n/en';
import { nb } from '../src/lib/i18n/nb';

const { directory, origin, password, sql, createUser, startWorker } = await proofEnvironment();
const email = 'shelf-ui@example.test', staffId = await createUser(email);
await sql(`INSERT INTO app.staff_members(auth_user_id,display_name) VALUES ('${staffId}', 'Shelf UI operator')`);
const cabinetId = await sql('SELECT id FROM app.cabinets WHERE inner_rows=12 AND inner_cols=4 AND NOT is_archived ORDER BY outer_row,outer_col LIMIT 1');
const binId = async (row: number, col: number) => sql(`SELECT id FROM app.bins WHERE cabinet_id='${cabinetId}' AND inner_row=${row} AND inner_col=${col} AND NOT is_archived`);
const first = await binId(1, 1), swapFirst = await binId(1, 4), swapSecond = await binId(2, 4);
let context: BrowserContext | undefined;
const { ready, close } = await startWorker(() => context);
const artifacts = resolve('test-results/shelf');
await mkdir(artifacts, { recursive: true });
const errors: string[] = [];
const m = en.adminShelf;
// One CSS pixel plus floating-point noise from browser bounding-box coordinates.
const pixelTolerance = 1 + 1e-5;
async function center(locator: Locator) {
  await locator.scrollIntoViewIfNeeded();
  const box = await locator.boundingBox(); assert.ok(box);
  return { x: box.x + box.width / 2, y: box.y + box.height / 2 };
}
async function startMove(page: Page, handle: Locator, x: number, y: number) {
  const start = await center(handle);
  await page.mouse.move(start.x, start.y); await page.mouse.down();
  await page.mouse.move(start.x + x, start.y + y, { steps: 5 });
}
async function dragSwap(page: Page, source: Locator, target: Locator) {
  await source.scrollIntoViewIfNeeded(); await target.scrollIntoViewIfNeeded();
  const sourceBox = await source.boundingBox(), targetBox = await target.boundingBox(); assert.ok(sourceBox && targetBox);
  const start = { x: sourceBox.x + sourceBox.width * .35, y: sourceBox.y + sourceBox.height * .4 };
  const original = await source.locator('.drawer').boundingBox(); assert.ok(original);
  const destination = { x: targetBox.x + targetBox.width / 2, y: targetBox.y + targetBox.height / 2 };
  await page.mouse.move(start.x, start.y); await page.mouse.down();
  await page.mouse.move(destination.x, destination.y, { steps: 8 });
  const lifted = page.locator('[data-drawer-drag-preview]');
  await expect(lifted).toBeVisible();
  await expect(source.locator('.drawer')).toHaveCSS('visibility', 'hidden');
  await expect(source).toHaveClass(/border-dashed/);
  const floating = await lifted.boundingBox(); assert.ok(floating);
  expect(Math.abs(floating.x - (original.x + destination.x - start.x))).toBeLessThanOrEqual(pixelTolerance);
  expect(Math.abs(floating.y - (original.y + destination.y - start.y))).toBeLessThanOrEqual(pixelTolerance);
  expect(floating.width).toBeCloseTo(original.width, 0); expect(floating.height).toBeCloseTo(original.height, 0);
  expect(await lifted.evaluate(element => getComputedStyle(element).pointerEvents)).toBe('none');
  await expect(target.locator('.drawer')).toHaveClass(/outline-dashed/);
  // The lifted drawer stays visible beyond the scroll region, without intercepting pointer targets.
  const viewport = await source.locator('xpath=ancestor::*[contains(@class, "shelf-viewport")]').boundingBox(); assert.ok(viewport);
  const outside = { x: viewport.x - 12, y: destination.y };
  await page.mouse.move(outside.x, outside.y, { steps: 3 });
  expect(Math.abs((await lifted.boundingBox())!.x - (original.x + outside.x - start.x))).toBeLessThanOrEqual(pixelTolerance);
  expect(await lifted.evaluate(element => {
    const box = element.getBoundingClientRect();
    return document.elementsFromPoint(box.left + box.width / 2, box.top + box.height / 2).every(hit => !element.contains(hit));
  })).toBe(true);
  await page.mouse.move(destination.x, destination.y, { steps: 3 });
  await expect(target.locator('.drawer')).toHaveClass(/outline-dashed/);
}
try {
  await ready();
  context = await firefox.launchPersistentContext(`${directory}/profile`, { headless: true, ignoreHTTPSErrors: false, hasTouch: true });
  context.on('page', tab => tab.on('pageerror', error => errors.push(error.message)));
  const page = await context.newPage();
  await page.goto(`${origin}/en/admin/login`);
  await page.getByLabel(fieldLabel('Email address')).fill(email);
  await page.getByLabel(fieldLabel('Password')).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('heading', { name: en.admin.overview, exact: true })).toBeVisible();
  await page.goto(`${origin}/en/admin/shelf`);
  await page.locator(`[data-item-id="${cabinetId}"]`).click();
  const editor = page.locator('section[data-cabinet-editor]');
  const picker = page.getByRole('dialog');
  await expect(editor).toBeVisible();
  await expect(picker).toHaveCount(0);
  // Drawer actions belong to a selected drawer; none is selected yet.
  const moveDrawer = editor.getByRole('button', { name: m.moveDrawer, exact: true });
  const archiveDrawer = editor.getByRole('button', { name: m.archiveBin, exact: true });
  await expect(moveDrawer).toHaveCount(0);
  await page.screenshot({ path: `${artifacts}/editor-initial.png` });
  const rows = editor.getByRole('slider', { name: m.resizeRows, exact: true });
  const cols = editor.getByRole('slider', { name: m.resizeCols, exact: true });
  await expect(rows).toHaveAttribute('aria-valuenow', '12');
  await expect(editor.getByText(m.grid(12, 4), { exact: true })).toBeVisible();
  await rows.evaluate(element => element.setAttribute('data-proof-persistent', 'true'));
  const refreshed = Promise.all(['amp_cabinets', 'amp_bins', 'amp_products'].map(table => page.waitForResponse(response => response.url().includes(`/${table}?`) && response.ok())));
  await page.evaluate(() => window.dispatchEvent(new Event('focus'))); await refreshed;
  await expect(rows).toBeEnabled();
  await expect(rows).toHaveAttribute('data-proof-persistent', 'true');
  const frameLocator = editor.locator('.cabinet-frame');
  const initialFrame = await frameLocator.boundingBox(), rowGrip = await rows.boundingBox(), colGrip = await cols.boundingBox(); assert.ok(initialFrame && rowGrip && colGrip);
  expect(Math.abs(rowGrip.y + rowGrip.height / 2 - initialFrame.y)).toBeLessThanOrEqual(pixelTolerance);
  expect(Math.abs(colGrip.x + colGrip.width / 2 - initialFrame.x - initialFrame.width)).toBeLessThanOrEqual(pixelTolerance);
  expect(initialFrame.height).toBeCloseTo(384, 0);
  await rows.focus(); await page.keyboard.press('ArrowUp'); await expect(rows).toHaveAttribute('aria-valuenow', '13');
  await page.keyboard.press('ArrowDown'); await expect(rows).toHaveAttribute('aria-valuenow', '12');
  await startMove(page, rows, 0, -40);
  await expect(rows).not.toHaveAttribute('aria-valuenow', '12');
  const activeRows = await rows.boundingBox(), activeFrame = await frameLocator.boundingBox(); assert.ok(activeRows && activeFrame);
  expect(activeFrame.height).toBeCloseTo(initialFrame.height, 0);
  expect(Math.abs(activeRows.y + activeRows.height / 2 - activeFrame.y)).toBeLessThanOrEqual(pixelTolerance);
  await rows.dispatchEvent('pointercancel', { pointerId: 1, pointerType: 'mouse' }); await page.mouse.up(); await expect(page.locator('[data-drawer-drag-preview]')).toHaveCount(0);
  await expect(rows).toHaveAttribute('aria-valuenow', '12');
  await startMove(page, rows, 0, -40); await page.keyboard.press('Escape'); await page.mouse.up(); await expect(page.locator('[data-drawer-drag-preview]')).toHaveCount(0);
  await expect(editor).toBeVisible(); await expect(rows).toHaveAttribute('aria-valuenow', '12');
  const frame = await editor.locator('.cabinet-frame').boundingBox(); assert.ok(frame);
  const cellBefore = await editor.locator(`[data-item-id="${first}"]`).boundingBox(); assert.ok(cellBefore);
  await startMove(page, cols, 64, 0);
  await expect(cols).toHaveAttribute('aria-valuenow', '5');
  const liveFrame = await frameLocator.boundingBox(), liveCell = await editor.locator(`[data-item-id="${first}"]`).boundingBox(); assert.ok(liveFrame && liveCell);
  const activeCols = await cols.boundingBox(); assert.ok(activeCols);
  expect(Math.abs(activeCols.x + activeCols.width / 2 - liveFrame.x - liveFrame.width)).toBeLessThanOrEqual(pixelTolerance);
  expect(activeCols.y + activeCols.height / 2).toBeCloseTo(liveFrame.y + liveFrame.height / 2, 0);
  expect(liveFrame.width - frame.width).toBeCloseTo(64, 0); expect(liveFrame.height).toBeCloseTo(frame.height, 0);
  expect(Math.abs(liveCell.width - cellBefore.width)).toBeLessThan(1);
  await page.keyboard.press('Escape'); await page.mouse.up(); await expect(page.locator('[data-drawer-drag-preview]')).toHaveCount(0);
  await expect(cols).toHaveAttribute('aria-valuenow', '4'); expect((await frameLocator.boundingBox())!.width).toBeCloseTo(frame.width, 0);
  await startMove(page, cols, 64, 0); await page.mouse.up(); await expect(page.locator('[data-drawer-drag-preview]')).toHaveCount(0);
  await expect(cols).toHaveAttribute('aria-valuenow', '5');
  await cols.focus(); await page.keyboard.press('ArrowLeft'); await expect(cols).toHaveAttribute('aria-valuenow', '4');
  await editor.locator(`[data-item-id="${first}"]`).click();
  const width = editor.getByRole('slider', { name: m.resizeHandle, exact: true });
  await width.focus(); await page.keyboard.press('ArrowRight'); await expect(width).toHaveAttribute('aria-valuenow', '2');
  expect(await sql(`SELECT col_span FROM app.bins WHERE id='${first}'`)).toBe('1');
  await expect(page.getByRole('button', { name: m.newCabinet, exact: true })).toBeDisabled();
  await expect(page.locator('section[aria-labelledby="wall-title"] [data-item-id]').first()).toBeDisabled();
  await dragSwap(page, editor.locator(`[data-item-id="${swapFirst}"]`), editor.locator(`[data-item-id="${swapSecond}"]`)); await page.mouse.up(); await expect(page.locator('[data-drawer-drag-preview]')).toHaveCount(0);
  await expect(editor.getByText(m.saveBeforeSwap, { exact: true })).toBeVisible();
  await expect(page.getByRole('alertdialog')).toHaveCount(0);
  const savedLayout = page.waitForResponse(response => response.url().includes('/rpc/amp_save_shelf_layout') && response.ok());
  await editor.getByRole('button', { name: m.save, exact: true }).click(); await savedLayout;
  await expect(editor).toBeVisible();
  await expect(rows).toHaveAttribute('aria-valuenow', '12');
  expect(await sql(`SELECT col_span FROM app.bins WHERE id='${first}'`)).toBe('2');
  await expect(editor.getByRole('button', { name: m.discardChanges, exact: true })).toBeHidden();
  console.log('PASS: inline editor; keyboard/pointer grid resizing and cancellation; drawer widening saves through real layout RPC without closing editor');

  await page.locator(`[data-item-id="${first}"]`).click();
  await page.getByRole('slider', { name: m.resizeHandle, exact: true }).focus(); await page.keyboard.press('ArrowRight');
  await expect(editor).toBeVisible();
  await expect(editor.getByRole('slider', { name: m.resizeHandle, exact: true })).toHaveAttribute('aria-valuenow', '3');
  await editor.getByRole('button', { name: m.discardChanges, exact: true }).click(); await expect(editor).toBeVisible();
  await editor.locator(`[data-item-id="${first}"]`).click();
  await expect(editor.getByRole('slider', { name: m.resizeHandle, exact: true })).toHaveAttribute('aria-valuenow', '2');
  expect(await sql(`SELECT col_span FROM app.bins WHERE id='${first}'`)).toBe('2');
  await expect(editor.getByRole('button', { name: m.discardChanges, exact: true })).toBeHidden();
  const source = page.locator(`[data-item-id="${swapFirst}"]`), target = page.locator(`[data-item-id="${swapSecond}"]`);
  const beforeTouchViewport = page.viewportSize()!;
  await page.setViewportSize({ width: 360, height: 640 });
  await expect(source).toHaveCSS('touch-action', 'auto');
  await source.click();
  const touchHandle = page.locator('.drawer-move-handle');
  await expect(touchHandle).toHaveCSS('touch-action', 'none');
  await startMove(page, touchHandle, 12, 12);
  await expect(page.locator('[data-drawer-drag-preview]')).toBeVisible();
  await page.keyboard.press('Escape'); await page.mouse.up();
  await expect(page.locator('[data-drawer-drag-preview]')).toHaveCount(0);
  await page.setViewportSize(beforeTouchViewport);
  const swaps: unknown[] = [];
  page.on('request', request => { if (request.url().includes('/rpc/amp_swap_bins') && request.method() === 'POST') swaps.push(request.postDataJSON()); });
  await dragSwap(page, source, target); await page.keyboard.press('Escape'); await page.mouse.up(); await expect(page.locator('[data-drawer-drag-preview]')).toHaveCount(0);
  await expect(page.getByRole('alertdialog')).toHaveCount(0); expect(swaps).toHaveLength(0);
  await dragSwap(page, source, target); await source.dispatchEvent('pointercancel', { pointerId: 1, pointerType: 'mouse' }); await page.mouse.up(); await expect(page.locator('[data-drawer-drag-preview]')).toHaveCount(0);
  await expect(page.getByRole('alertdialog')).toHaveCount(0); expect(swaps).toHaveLength(0);
  await dragSwap(page, source, target); await page.mouse.up(); await expect(page.locator('[data-drawer-drag-preview]')).toHaveCount(0);
  const confirm = page.getByRole('alertdialog'); await expect(confirm).toBeVisible();
  await confirm.getByRole('button', { name: m.cancelAction, exact: true }).click();
  expect(swaps).toHaveLength(0); await expect(page.getByText(m.positionsSwapped, { exact: true })).toHaveCount(0);
  await dragSwap(page, source, target); await page.mouse.up(); await expect(page.locator('[data-drawer-drag-preview]')).toHaveCount(0);
  let acknowledge!: () => void, reached!: () => void;
  const ack = new Promise<void>(resolve => acknowledge = resolve), committed = new Promise<void>(resolve => reached = resolve);
  await page.route('**/rpc/amp_swap_bins', async route => { const response = await route.fetch(); reached(); await ack; await route.fulfill({ response }); });
  const savedSwap = page.waitForResponse(response => response.url().includes('/rpc/amp_swap_bins') && response.ok());
  await confirm.getByRole('button', { name: m.confirmAction, exact: true }).click();
  await committed; await expect(page.getByText(m.positionsSwapped, { exact: true })).toHaveCount(0); acknowledge(); await savedSwap;
  await page.unroute('**/rpc/amp_swap_bins'); await expect(page.getByText(m.positionsSwapped, { exact: true })).toBeVisible();
  await expect(confirm).toHaveCount(0); expect(swaps).toHaveLength(1);
  expect(await sql(`SELECT inner_row FROM app.bins WHERE id='${swapFirst}'`)).toBe('2');
  expect(await sql(`SELECT inner_row FROM app.bins WHERE id='${swapSecond}'`)).toBe('1');
  await source.click(); await page.locator('.drawer-move-handle').focus(); await page.keyboard.press('Enter');
  await expect(picker).toHaveCount(0); await expect(editor.getByText(m.chooseSwap, { exact: true })).toBeVisible();
  await page.keyboard.press('Escape'); await expect(editor.getByText(m.chooseSwap, { exact: true })).toBeHidden();
  const moveHandle = await center(page.locator('.drawer-move-handle')); await page.touchscreen.tap(moveHandle.x, moveHandle.y);
  await expect(picker).toHaveCount(0); await expect(editor.getByText(m.chooseSwap, { exact: true })).toBeVisible();
  await target.click(); await expect(confirm).toBeVisible();
  await confirm.getByRole('button', { name: m.cancelAction, exact: true }).click(); expect(swaps).toHaveLength(1);
  await page.keyboard.press('Escape');
  const editorSource = editor.locator(`[data-item-id="${swapFirst}"]`), editorTarget = editor.locator(`[data-item-id="${swapSecond}"]`);
  await dragSwap(page, editorSource, editorTarget); await page.mouse.up(); await expect(page.locator('[data-drawer-drag-preview]')).toHaveCount(0);
  await expect(confirm).toBeVisible();
  const editorSwap = page.waitForResponse(response => response.url().includes('/rpc/amp_swap_bins') && response.ok());
  await confirm.getByRole('button', { name: m.confirmAction, exact: true }).click(); await editorSwap;
  await expect(editor).toBeVisible(); expect(swaps).toHaveLength(2);
  expect(await sql(`SELECT inner_row FROM app.bins WHERE id='${swapFirst}'`)).toBe('1');
  expect(await sql(`SELECT inner_row FROM app.bins WHERE id='${swapSecond}'`)).toBe('2');
  console.log('PASS: drawer drag target outline, Escape/pointer cancellation, confirmation cancel/commit, persisted swap and keyboard/touch inline target selection');

  await source.click(); await moveDrawer.click();
  await expect(editor.getByText(m.chooseSwap, { exact: true })).toBeVisible();
  await editor.getByRole('button', { name: m.cancelAction, exact: true }).click();
  await expect(editor.getByText(m.chooseSwap, { exact: true })).toBeHidden();
  await moveDrawer.click();
  const anotherCabinet = page.locator(`section[aria-labelledby="wall-title"] [data-item-id]:not([data-item-id="${cabinetId}"])`).first();
  await expect(anotherCabinet).toBeEnabled(); await anotherCabinet.click();
  await expect(editor.getByText(m.chooseSwap, { exact: true })).toBeVisible();
  await editor.locator('[data-item-id]').first().click(); await expect(confirm).toBeVisible();
  await confirm.getByRole('button', { name: m.cancelAction, exact: true }).click(); expect(swaps).toHaveLength(2);
  await page.keyboard.press('Escape'); await page.locator(`[data-item-id="${cabinetId}"]`).click(); await source.click();
  await expect(editor.getByText(m.noProducts, { exact: true })).toBeVisible();
  await expect(archiveDrawer).toBeEnabled();
  // A drafted layout change blocks immediate drawer commands until it is saved or discarded.
  await rows.focus(); await page.keyboard.press('ArrowUp');
  await expect(moveDrawer).toBeDisabled(); await expect(archiveDrawer).toBeDisabled();
  await editor.getByRole('button', { name: m.discardChanges, exact: true }).click();
  await source.click(); await expect(archiveDrawer).toBeEnabled();
  await sql(`INSERT INTO app.products(code,name_nb,name_en,unit_code,stock_step,sale_step,sale_unit_price_nok,bin_id) VALUES ('SHELF-PROOF','Testdel','Test part','pcs',1,1,0,'${swapFirst}')`);
  const occupiedRead = Promise.all(['amp_cabinets', 'amp_bins', 'amp_products'].map(table => page.waitForResponse(response => response.url().includes(`/${table}?`) && response.ok())));
  await page.evaluate(() => window.dispatchEvent(new Event('focus'))); await occupiedRead;
  await expect(source).toBeEnabled(); await source.click();
  await expect(archiveDrawer).toBeDisabled();
  await expect(editor.getByRole('button', { name: m.narrowDrawer, exact: true })).toBeDisabled();
  await expect(editor.getByText('SHELF-PROOF', { exact: true })).toBeVisible();
  console.log('PASS: drawer actions beside the selected drawer: move, draft guard, contents and occupied archive guard');

  const vacantBin = await binId(3, 4);
  const contentsBeforeMove = await sql(`SELECT coalesce(jsonb_agg(id ORDER BY id), '[]') FROM app.products WHERE bin_id='${swapFirst}'`);
  await editor.locator(`[data-item-id="${vacantBin}"]`).click();
  await archiveDrawer.click(); await expect(confirm).toBeVisible();
  const archived = page.waitForResponse(response => response.url().includes('/amp_bins?') && response.request().method() === 'PATCH' && response.ok());
  await confirm.getByRole('button', { name: m.confirmAction, exact: true }).click(); await archived;
  await expect(editor.locator(`[data-item-id="${vacantBin}"]`)).toHaveCount(0);
  expect(await sql(`SELECT is_archived FROM app.bins WHERE id='${vacantBin}'`)).toBe('t');
  await source.click(); await moveDrawer.click();
  await editor.locator('[data-item-id="vacant:3:4"]').click(); await expect(confirm).toBeVisible();
  await expect(picker).toHaveCount(0);
  const moved = page.waitForResponse(response => response.url().includes('/amp_bins?') && response.request().method() === 'PATCH' && response.ok());
  await confirm.getByRole('button', { name: m.confirmAction, exact: true }).click(); await moved;
  await expect(editor.getByText(m.chooseSwap, { exact: true })).toBeHidden();
  expect(await sql(`SELECT inner_row=3 AND inner_col=4 AND NOT is_archived FROM app.bins WHERE id='${swapFirst}'`)).toBe('t');
  expect(await sql(`SELECT coalesce(jsonb_agg(id ORDER BY id), '[]') FROM app.products WHERE bin_id='${swapFirst}'`)).toBe(contentsBeforeMove);
  expect(await sql(`SELECT count(*) FROM app.bins WHERE cabinet_id='${cabinetId}' AND inner_row=1 AND inner_col=4 AND NOT is_archived`)).toBe('0');
  console.log('PASS: archive empty drawer then move assigned drawer into vacant position, preserving identity and products');

  for (const locale of ['nb', 'en'] as const) for (const colorScheme of ['light', 'dark'] as const) for (const width of [360, 1280]) {
    const messages = (locale === 'nb' ? nb : en).adminShelf;
    await page.setViewportSize({ width, height: width === 360 ? 640 : 900 }); await page.emulateMedia({ colorScheme, reducedMotion: 'reduce' });
    await page.goto(`${origin}${locale === 'nb' ? '' : '/en'}/admin/shelf`);
    await page.locator(`[data-item-id="${cabinetId}"]`).click();
    await page.locator(`[data-item-id="${swapFirst}"]`).click();
    await page.locator('.drawer-move-handle').scrollIntoViewIfNeeded();
    expect(await editor.locator('.shelf-viewport').evaluate(element => element.scrollWidth <= element.clientWidth), `Standard cabinet fits ${locale}/${colorScheme}/${width}`).toBe(true);
    await page.screenshot({ path: `${artifacts}/drawers-${locale}-${colorScheme}-${width}.png` });
    await expect(picker).toHaveCount(0);
    await expect(editor.getByRole('slider', { name: messages.resizeRows, exact: true })).toBeVisible();
    // Admin pages carry no floating buyer scanner, so nothing covers the shelf grips (design-system §4.1).
    await expect(page.locator('.scanner-trigger')).toHaveCount(0);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
    expect(await editor.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
    await page.screenshot({ path: `${artifacts}/cabinet-${locale}-${colorScheme}-${width}.png` });
  }
  expect(errors).toEqual([]);
  console.log('PASS: localized light/dark inline cabinet editors at 360/1280px with no page or editor horizontal overflow');

  const retiringCabinet = randomUUID(), retiringBins = [randomUUID(), randomUUID()];
  await sql(`INSERT INTO app.cabinets(id,code,outer_row,outer_col,inner_rows,inner_cols) VALUES ('${retiringCabinet}','C-${retiringCabinet}',3,1,1,2)`);
  for (const [index, id] of retiringBins.entries()) {
    await sql(`INSERT INTO app.bins(id,code,cabinet_id,inner_row,inner_col) VALUES ('${id}','B-${id}','${retiringCabinet}',1,${index + 1})`);
  }
  await page.reload();
  await page.locator(`section[aria-labelledby="wall-title"] [data-item-id="${retiringCabinet}"]`).click();
  await editor.getByRole('button', { name: m.archiveCabinetWithDrawers, exact: true }).click();
  await expect(confirm).toContainText(m.archiveCabinetWithDrawersConfirm(2));
  const cabinetArchived = page.waitForResponse(response => response.url().includes('/rpc/amp_archive_empty_cabinet') && response.ok());
  await confirm.getByRole('button', { name: m.confirmAction, exact: true }).click(); await cabinetArchived;
  await expect(page.locator(`section[aria-labelledby="wall-title"] [data-item-id="${retiringCabinet}"]`)).toHaveCount(0);
  expect(await sql(`SELECT is_archived FROM app.cabinets WHERE id='${retiringCabinet}'`)).toBe('t');
  expect(await sql(`SELECT count(*) FROM app.bins WHERE id IN ('${retiringBins.join("','")}') AND is_archived`)).toBe('2');
  console.log('PASS: cabinet and two empty drawers archive through one confirmed RPC');

  // Move cabinet: the wall picker offers vacant positions as well as cabinets to swap with.
  const binsBeforeMove = await sql(`SELECT coalesce(jsonb_agg(id ORDER BY id), '[]') FROM app.bins WHERE cabinet_id='${cabinetId}' AND NOT is_archived`);
  await page.locator(`section[aria-labelledby="wall-title"] [data-item-id="${cabinetId}"]`).click();
  await editor.getByRole('button', { name: m.moveCabinet, exact: true }).click();
  const mover = page.getByRole('dialog', { name: m.moveCabinet, exact: true });
  await mover.getByRole('button', { name: `A3 · ${m.emptyDrawer}`, exact: true }).click();
  await expect(mover).toContainText(m.cabinet('A3'));
  const cabinetMoved = page.waitForResponse(response => response.url().includes('/amp_cabinets?') && response.request().method() === 'PATCH' && response.ok());
  await mover.getByRole('button', { name: m.move, exact: true }).click();
  await confirm.getByRole('button', { name: m.confirmAction, exact: true }).click(); await cabinetMoved;
  await expect(mover).toBeHidden();
  await expect(editor.getByRole('heading', { name: m.cabinet('A3'), exact: true })).toBeVisible();
  expect(await sql(`SELECT outer_row=3 AND outer_col=1 FROM app.cabinets WHERE id='${cabinetId}'`)).toBe('t');
  expect(await sql(`SELECT coalesce(jsonb_agg(id ORDER BY id), '[]') FROM app.bins WHERE cabinet_id='${cabinetId}' AND NOT is_archived`)).toBe(binsBeforeMove);
  expect(errors).toEqual([]);
  console.log('PASS: cabinet moves to a vacant wall position through the wall picker, keeping its drawers');
} catch (error) {
  for (const [index, page] of (context?.pages() ?? []).entries()) await captureFailure(page, artifacts, String(index), 'body');
  throw error;
} finally { await close(); }
